# Generated by Django 2.2.5 on 2019-12-24 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.IntegerField()),
                ('user', models.TextField()),
                ('view', models.BooleanField()),
                ('report', models.BooleanField()),
                ('manage', models.BooleanField()),
            ],
        ),
    ]
